#   Copyright (c) 2022 Samsung
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
log-level: debug
onborder-url: "http://127.0.0.1:9191"
mock-server: "127.0.0.1:9191"
getCharts-url: "http://127.0.0.1:9191/helmrepo/api/charts"
download-charts-url-format: "http://127.0.0.1:9191/helmrepo/charts/%s-%s.tgz"
getCharts-by-name-url: "http://127.0.0.1:9191/helmrepo/api/charts/%s"
getCharts-by-name-and-version-url: "http://127.0.0.1:9191/helmrepo/api/charts/%s/%s"
getXappHealth-url: "http://127.0.0.1:9191/ric/v1/health/alive/%s/%s"
customOnboard-url: "http://127.0.0.1:37019/api/charts"